create table if not exists reviews (
  id bigint generated by default as identity primary key,
  school_id text not null,
  rating int not null check (rating >= 1 and rating <= 5),
  review_text text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table reviews enable row level security;

create policy "Allow public insert"
on reviews for insert
to anon
with check (true);

create policy "Allow public read"
on reviews for select
to anon
using (true);
